# Site settings
title: objc-code
subtitle: "Journal of yiplee"
email: guoyinl@gmail.com
description: "来自一个 iOS 工程师的学习笔记"
baseurl: ""
url: "https://yiplee.github.io"
twitter_username: "yipleeyin"
github_username:  "yiplee"
instagram_username: "yiplee"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed
