# Site settings
title: objc-code
subtitle: "Journal of Cocoa"
email: guoyinl@gmail.com
description: "编程笔记"
baseurl: ""
url: "https://yiplee.github.io"
twitter_username: "yipleeyin"
github_username:  "yiplee"
instagram_username: "yiplee12"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

highlighter: rouge

# Sass
sass:
    style: :compressed
